# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import reslog
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1091, 808)
        Form.setStyleSheet("")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(-11, -1, 1111, 821))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(0, -10, 1101, 821))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setKerning(False)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("background: url(:/background/background/thiet-ke-cua-hang-van-phong-pham.jpg);\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"background-size: cover;\n"
"\n"
"\n"
"")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/background/background/thiet-ke-cua-hang-van-phong-pham.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(230, 180, 631, 441))
        self.label_3.setStyleSheet("background-color:rgba(0,0,0,100);\n"
"border-radius:20px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(510, 220, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_4.setFont(font)
        self.label_4.setMouseTracking(False)
        self.label_4.setStyleSheet("color:rgba(255,255,255,210);")
        self.label_4.setObjectName("label_4")
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        self.textEdit.setGeometry(QtCore.QRect(360, 290, 401, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("background-color: transparent; /* Nền hoàn toàn trong suốt */\n"
"    border: none; /* Không có viền xung quanh */\n"
"    border-bottom: 2px solid rgba(255, 255, 255, 0.7); /* Đường gạch dưới màu trắng mờ */\n"
"    border-radius: 0px; /* Không bo góc */\n"
"    padding: 10px 5px; /* Đệm bên trong */\n"
"    color: white; /* Màu chữ trắng để dễ đọc trên nền tối */\n"
"    font-size: 14px; /* Kích thước chữ */")
        self.textEdit.setObjectName("textEdit")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(360, 380, 401, 41))
        self.lineEdit.setStyleSheet("background-color: transparent;\n"
"    border: none;\n"
"    border-bottom: 1px solid white;\n"
"    padding: 8px 2px;\n"
"    color: white;\n"
"    font-size: 15px;")
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit.setObjectName("lineEdit")
        self.lg_btn = QtWidgets.QPushButton(self.widget)
        self.lg_btn.setGeometry(QtCore.QRect(360, 460, 401, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lg_btn.setFont(font)
        self.lg_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0.6);\n"
"    color: white;\n"
"    border: 1px solid white;\n"
"    border-radius: 8px;\n"
"    padding: 8px 16px;\n"
"    font-weight: bold;\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 107, 53, 0.8);\n"
"    border: 1px solid #ff6b35;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 107, 53, 1);\n"
"    border: 1px solid white;\n"
"}\n"
"")
        self.lg_btn.setCheckable(True)
        self.lg_btn.setObjectName("lg_btn")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(480, 530, 191, 16))
        self.label.setStyleSheet("QLabel {\n"
"    color: #ff6b35;  /* Màu cam đỏ */\n"
"    text-decoration: none;\n"
"    font-size: 10pt;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    color: #ff8c61;  /* Màu cam đỏ sáng hơn khi hover */\n"
"    text-decoration: underline;\n"
"}\n"
"")
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Login"))
        self.textEdit.setPlaceholderText(_translate("Form", "User Name"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Password"))
        self.lg_btn.setText(_translate("Form", "L o g I n"))
        self.label.setText(_translate("Form", "Forgot your password ?"))

