# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_offical.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main_log(object):
    def setupUi(self, Main_log):
        Main_log.setObjectName("Main_log")
        Main_log.resize(1100, 800)
        font = QtGui.QFont()
        font.setPointSize(10)
        Main_log.setFont(font)
        Main_log.setStyleSheet("#Main_log {\n"
"border-image: url(:/background/_1 (1).jpg);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Main_log)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setEnabled(True)
        self.widget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widget.setToolTipDuration(-1)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setVerticalSpacing(7)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 105, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(174, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.Container = QtWidgets.QWidget(self.widget)
        self.Container.setEnabled(True)
        self.Container.setStyleSheet("/* Áp dụng cho Container chính */\n"
"#Container {\n"
"    background-color: rgba(40, 40, 40, 180);\n"
"    border-radius: 10px;\n"
"    border: 1px solid rgba(60, 60, 60, 200);\n"
"    color: white;\n"
"}\n"
"\n"
"/* Đặt lại thuộc tính cho các widget con */\n"
"QLineEdit {\n"
"    background-color: rgba(255, 255, 255, 220);\n"
"    color: black;\n"
"    border: 1px solid gray;\n"
"    border-radius: 5px;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: rgba(70, 130, 180, 200);\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"")
        self.Container.setObjectName("Container")
        self.gridLayout = QtWidgets.QGridLayout(self.Container)
        self.gridLayout.setContentsMargins(150, 29, 150, 35)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 31, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(9, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(16)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.Container)
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("\n"
"color: rgb(255,255,255); /* Đổi thành màu trắng */\n"
"\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.Container)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setMinimumSize(QtCore.QSize(350, 50))
        self.lineEdit.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgba(255,255,255,200); /* Đổi thành màu trắng (255,255,255) với độ trong suốt 200 */\n"
"color: rgb(255,255,255); /* Đổi thành màu trắng */\n"
"padding-bottom: 7px;\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        spacerItem5 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.Container)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_2.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgba(255,255,255,200); /* Đổi thành màu trắng (255,255,255) với độ trong suốt 200 */\n"
"color: rgb(255,255,255); /* Đổi thành màu trắng */\n"
"padding-bottom: 7px;\n"
"")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem6 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.pushButton = QtWidgets.QPushButton(self.Container)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0.6);\n"
"    color: white;\n"
"    border: 1px solid white;\n"
"    border-radius: 8px;\n"
"    padding: 8px 16px;\n"
"    font-weight: bold;\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 107, 53, 0.8);\n"
"    border: 1px solid #ff6b35;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 107, 53, 1);\n"
"    border: 1px solid white;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.label_4 = QtWidgets.QLabel(self.Container)
        self.label_4.setMinimumSize(QtCore.QSize(0, 30))
        self.label_4.setStyleSheet("color: rgb(255, 165, 0);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 1, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 31, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem8, 2, 1, 1, 1)
        self.gridLayout_2.addWidget(self.Container, 1, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(174, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 1, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 137, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem10, 2, 1, 1, 1)
        self.gridLayout_3.addWidget(self.widget, 0, 0, 1, 1)
        Main_log.setCentralWidget(self.centralwidget)

        self.retranslateUi(Main_log)
        QtCore.QMetaObject.connectSlotsByName(Main_log)

    def retranslateUi(self, Main_log):
        _translate = QtCore.QCoreApplication.translate
        Main_log.setWindowTitle(_translate("Main_log", "MainWindow"))
        self.label_3.setText(_translate("Main_log", "WELCOME"))
        self.lineEdit.setPlaceholderText(_translate("Main_log", "User Name"))
        self.lineEdit_2.setPlaceholderText(_translate("Main_log", "Password"))
        self.pushButton.setText(_translate("Main_log", "L o g I n"))
        self.label_4.setText(_translate("Main_log", "Forgot your Password ?"))
import resource_log_rc
