# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_design/add_import.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 660)
        Form.setStyleSheet("#Form {\n"
"background: #F5F5F5;\n"
"border-bottom-radius : 10px;\n"
"border : 2px solid white ;\n"
"}")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-10, 0, 811, 61))
        self.label.setMinimumSize(QtCore.QSize(811, 61))
        self.label.setMaximumSize(QtCore.QSize(811, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    background-color:  rgba(40, 40, 40, 180); /* Nền xanh trong suốt */\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"\n"
"    padding: 8px 16px;\n"
"    \n"
"    /* Viền sáng */\n"
"    border: 1.5px solid rgba(255, 255, 255, 0.4);\n"
"    \n"
"    /* Đổ bóng - QSS hỗ trợ giới hạn */\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    \n"
"    /* Gradient xanh */\n"
"}\n"
"\n"
"")
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 70, 703, 581))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.line_id = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_id.setMinimumSize(QtCore.QSize(691, 35))
        self.line_id.setStyleSheet("QLineEdit {\n"
"    background-color: #ffffff; /* Màu nền trắng */\n"
"    border: 1px solid #cccccc; /* Viền xám nhạt */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 5px; /* Khoảng cách bên trong */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"/* Hiệu ứng khi ô nhập liệu được chọn */\n"
"QLineEdit:focus {\n"
"    border: 1px solid #4a90e2; /* Viền xanh khi focus */\n"
"    background-color: #e6f0fa; /* Nền xanh nhạt khi focus */\n"
"}")
        self.line_id.setObjectName("line_id")
        self.verticalLayout.addWidget(self.line_id)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.combo_box_ten_nhan_vien = QtWidgets.QComboBox(self.layoutWidget)
        self.combo_box_ten_nhan_vien.setMinimumSize(QtCore.QSize(691, 35))
        self.combo_box_ten_nhan_vien.setStyleSheet("QComboBox {\n"
"    background-color: #ffffff; /* Màu nền trắng */\n"
"    border: 1px solid #cccccc; /* Viền xám nhạt */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 5px; /* Khoảng cách bên trong */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"/* Hiệu ứng khi ô nhập liệu được chọn */\n"
"QComboBox:focus {\n"
"    border: 1px solid #4a90e2; /* Viền xanh khi focus */\n"
"    background-color: #e6f0fa; /* Nền xanh nhạt khi focus */\n"
"}")
        self.combo_box_ten_nhan_vien.setObjectName("combo_box_ten_nhan_vien")
        self.verticalLayout_2.addWidget(self.combo_box_ten_nhan_vien)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(12)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget = QtWidgets.QWidget(self.layoutWidget)
        self.widget.setMinimumSize(QtCore.QSize(696, 41))
        self.widget.setMaximumSize(QtCore.QSize(693, 41))
        self.widget.setStyleSheet("QLabel {\n"
"    color: rgba(50, 50, 50, 0.85); /* Màu chữ đậm nhưng hơi trong suốt */\n"
"    font-family: \"Segoe UI\", \"Roboto\", sans-serif; /* Font hiện đại */\n"
"    font-weight: 500; /* Độ đậm vừa phải */\n"
"    font-size: 18px; /* Kích thước phù hợp */\n"
"\n"
"    letter-spacing: 0.3px; /* Tăng khoảng cách chữ nhẹ */\n"
"    \n"
"    text-align: center;\n"
"    background-color: rgba(255, 255, 255, 0.1); /* Nền trắng trong suốt */\n"
"    border-radius: 6px; /* Bo góc */\n"
"    backdrop-filter: blur(5px); /* Hiệu ứng blur đặc trưng của glassmorphism */\n"
"    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.07); /* Đổ bóng tinh tế */\n"
"    border: 1px solid rgba(255, 255, 255, 0.18); /* Viền trắng trong suốt */\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 11, 0, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setMinimumSize(QtCore.QSize(191, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,Roboto,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel {\n"
"    color: black; /* Màu chữ nâu vintage */ /* Chữ in nghiêng */\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"\n"
"    text-align: center;\n"
"}\n"
"\n"
"\n"
"")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.them_san_pham_pn_btn = QtWidgets.QPushButton(self.widget)
        self.them_san_pham_pn_btn.setMinimumSize(QtCore.QSize(133, 21))
        self.them_san_pham_pn_btn.setStyleSheet("QPushButton {\n"
"    background-color:  rgba(40, 40, 40, 180); /* Nền xanh trong suốt */\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    border-radius: 10;\n"
"    \n"
"    /* Viền sáng */\n"
"    border: 1.5px solid rgba(255, 255, 255, 0.4);\n"
"    \n"
"    /* Đổ bóng - QSS hỗ trợ giới hạn */\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    \n"
"    /* Gradient xanh */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(30, 170, 255, 0.5); /* Xanh sáng hơn khi hover */\n"
"    border: 1.5px solid rgba(255, 255, 255, 0.6);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 120, 200, 0.4);\n"
"    border: 1.5px solid rgba(255, 255, 255, 0.3);\n"
"    padding-top: 9px; /* Tạo hiệu ứng nhấn xuống */\n"
"    padding-left: 17px;\n"
"}\n"
"")
        self.them_san_pham_pn_btn.setObjectName("them_san_pham_pn_btn")
        self.gridLayout.addWidget(self.them_san_pham_pn_btn, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(172, 16, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(167, 16, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.widget)
        self.table_san_pham_pn = QtWidgets.QTableWidget(self.layoutWidget)
        self.table_san_pham_pn.setMinimumSize(QtCore.QSize(691, 161))
        self.table_san_pham_pn.setStyleSheet("/* Tổng thể bảng với phong cách Glassmorphism */\n"
"QTableWidget {\n"
"    background-color:  rgba(40, 40, 40, 180); /* Nền đen mờ, tăng độ trong suốt */\n"
"    border: 1px solid rgba(255, 255, 255, 0.2); /* Viền trắng mờ nhẹ */\n"
"    border-radius: 10px; /* Bo góc mềm mại */\n"
"    color: #ffffff; /* Chữ trắng để nổi bật */\n"
"    font-family: \"Arial\", sans-serif;\n"
"    font-size: 14px;\n"
"    gridline-color: transparent;\n"
"}\n"
"\n"
"/* Tiêu đề cột (header) */\n"
"QHeaderView::section {\n"
"    background-color: rgba(30, 30, 30, 180);\n"
" /* Nền header đen mờ hơn một chút */\n"
"    color: #ffffff;\n"
"    padding: 8px;\n"
"    border: none;\n"
"    border-bottom: 1px solid rgba(255, 255, 255, 0.2);\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Hiệu ứng hover cho tiêu đề */\n"
"QHeaderView::section:hover {\n"
"    background-color: rgba(0, 0, 0, 0.6); /* Sáng nhẹ khi hover */\n"
"    transition: background-color 0.3s ease; /* Hiệu ứng chuyển màu mượt */\n"
"}\n"
"\n"
"/* Các ô trong bảng */\n"
"QTableWidget::item {\n"
"    padding: 8px;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/* Hiệu ứng khi chọn ô */\n"
"QTableWidget::item:selected {\n"
"    background-color: rgba(66, 165, 245, 0.4); /* Màu xanh dương mờ khi chọn */\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* Hiệu ứng hover cho ô */\n"
"QTableWidget::item:hover {\n"
"    background-color: rgba(255, 255, 255, 0.1); /* Sáng nhẹ khi rê chuột */\n"
"    transition: background-color 0.3s ease; /* Chuyển màu mượt mà */\n"
"}\n"
"\n"
"/* Thanh cuộn dọc */\n"
"QScrollBar:vertical {\n"
"    background: rgba(0, 0, 0, 0.3); /* Nền đen mờ hơn */\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: linear-gradient(to bottom, rgba(66, 165, 245, 0.6), rgba(30, 136, 229, 0.6)); /* Gradient xanh dương mờ */\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: linear-gradient(to bottom, rgba(100, 181, 246, 0.7), rgba(66, 165, 245, 0.7)); /* Sáng hơn khi hover */\n"
"    transition: background 0.3s ease;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* Thanh cuộn ngang */\n"
"QScrollBar:horizontal {\n"
"    background: rgba(0, 0, 0, 0.3); /* Nền đen mờ hơn */\n"
"    height: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: linear-gradient(to right, rgba(66, 165, 245, 0.6), rgba(30, 136, 229, 0.6)); /* Gradient xanh dương mờ */\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: linear-gradient(to right, rgba(100, 181, 246, 0.7), rgba(66, 165, 245, 0.7)); /* Sáng hơn khi hover */\n"
"    transition: background 0.3s ease;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal,\n"
"QScrollBar::sub-line:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal,\n"
"QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}")
        self.table_san_pham_pn.setObjectName("table_san_pham_pn")
        self.table_san_pham_pn.setColumnCount(8)
        self.table_san_pham_pn.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_san_pham_pn.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_san_pham_pn.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_san_pham_pn.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_san_pham_pn.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_san_pham_pn.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_san_pham_pn.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_san_pham_pn.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_san_pham_pn.setHorizontalHeaderItem(7, item)
        self.verticalLayout_6.addWidget(self.table_san_pham_pn)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 1, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(17)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 9, -1, -1)
        self.horizontalLayout_2.setSpacing(90)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.line_tong_tien = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_tong_tien.setMinimumSize(QtCore.QSize(271, 35))
        self.line_tong_tien.setStyleSheet("QLineEdit {\n"
"    background-color: #ffffff; /* Màu nền trắng */\n"
"    border: 1px solid #cccccc; /* Viền xám nhạt */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 5px; /* Khoảng cách bên trong */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"/* Hiệu ứng khi ô nhập liệu được chọn */\n"
"QLineEdit:focus {\n"
"    border: 1px solid #4a90e2; /* Viền xanh khi focus */\n"
"    background-color: #e6f0fa; /* Nền xanh nhạt khi focus */\n"
"}")
        self.line_tong_tien.setObjectName("line_tong_tien")
        self.verticalLayout_4.addWidget(self.line_tong_tien)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        spacerItem2 = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.them_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.them_btn.setMinimumSize(QtCore.QSize(80, 40))
        self.them_btn.setStyleSheet("QPushButton {\n"
"    background-color:  rgba(30, 170, 255, 0.7); /* Nền xanh trong suốt */\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    border-radius: 16px;\n"
"    padding: 8px 16px;\n"
"    \n"
"    /* Viền sáng */\n"
"    border: 1.5px solid rgba(255, 255, 255, 0.4);\n"
"    \n"
"    /* Đổ bóng - QSS hỗ trợ giới hạn */\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    \n"
"    /* Gradient xanh */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(30, 170, 255, 0.5); /* Xanh sáng hơn khi hover */\n"
"    border: 1.5px solid rgba(255, 255, 255, 0.6);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 120, 200, 0.4);\n"
"    border: 1.5px solid rgba(255, 255, 255, 0.3);\n"
"    padding-top: 9px; /* Tạo hiệu ứng nhấn xuống */\n"
"    padding-left: 17px;\n"
"}\n"
"")
        self.them_btn.setObjectName("them_btn")
        self.horizontalLayout_3.addWidget(self.them_btn)
        self.huy_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.huy_btn.setMinimumSize(QtCore.QSize(80, 40))
        self.huy_btn.setStyleSheet("#huy_btn {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #d9d9d9;\n"
"    font-family: Arial, sans-serif;\n"
"    font-size: 12px;\n"
"    border-radius: 10px;\n"
"    padding: 5px 15px; /* Khoảng cách trong nút */\n"
"}\n"
"\n"
"/* Hover effect */\n"
"#huy_btn:hover {\n"
"    background-color: #f5f5f5;  /* Nhẹ hơn để tạo hiệu ứng phản hồi */\n"
"    border: 1px solid #a0a0a0;  /* Viền đậm hơn một chút khi hover */\n"
"    color: black;\n"
"}\n"
"")
        self.huy_btn.setObjectName("huy_btn")
        self.horizontalLayout_3.addWidget(self.huy_btn)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(508, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        spacerItem4 = QtWidgets.QSpacerItem(699, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "     THÊM PHIẾU NHẬP"))
        self.label_2.setText(_translate("Form", "ID Phiếu nhập : "))
        self.line_id.setPlaceholderText(_translate("Form", "  ID Phiếu nhập...."))
        self.label_3.setText(_translate("Form", "Tên nhân viên nhập hàng  : "))
        self.label_5.setText(_translate("Form", "    Danh sách sản phẩm : "))
        self.them_san_pham_pn_btn.setText(_translate("Form", "Thêm sản phẩm "))
        item = self.table_san_pham_pn.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.table_san_pham_pn.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Tên sản phẩm"))
        item = self.table_san_pham_pn.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Danh mục"))
        item = self.table_san_pham_pn.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Kho"))
        item = self.table_san_pham_pn.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Số lượng"))
        item = self.table_san_pham_pn.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Đơn vị"))
        item = self.table_san_pham_pn.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Giá nhập"))
        item = self.table_san_pham_pn.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Chỉnh sửa "))
        self.label_6.setText(_translate("Form", "Tổng tiền : "))
        self.line_tong_tien.setPlaceholderText(_translate("Form", "  Tổng tiền..."))
        self.them_btn.setText(_translate("Form", "Thêm "))
        self.huy_btn.setText(_translate("Form", "Hủy"))
