# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_design/add_employee.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 620)
        Form.setMinimumSize(QtCore.QSize(0, 620))
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("#Form {\n"
"background: #F5F5F5;\n"
"border-bottom-radius : 10px;\n"
"border : 2px solid white ;\n"
"}")
        self.them_sua_label = QtWidgets.QLabel(Form)
        self.them_sua_label.setGeometry(QtCore.QRect(0, 0, 800, 45))
        self.them_sua_label.setMinimumSize(QtCore.QSize(800, 45))
        self.them_sua_label.setStyleSheet("QLabel {\n"
"    background-color:  rgba(40, 40, 40, 180); /* Nền xanh trong suốt */\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"\n"
"    padding: 8px 16px;\n"
"    \n"
"    /* Viền sáng */\n"
"    border: 1.5px solid rgba(255, 255, 255, 0.4);\n"
"    \n"
"    /* Đổ bóng - QSS hỗ trợ giới hạn */\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    \n"
"    /* Gradient xanh */\n"
"}\n"
"\n"
"")
        self.them_sua_label.setText("")
        self.them_sua_label.setObjectName("them_sua_label")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 60, 801, 542))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(20, 0, 20, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.line_id = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_id.setMinimumSize(QtCore.QSize(300, 35))
        self.line_id.setStyleSheet("QLineEdit {\n"
"    background-color: #ffffff; /* Màu nền trắng */\n"
"    border: 1px solid #cccccc; /* Viền xám nhạt */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 5px; /* Khoảng cách bên trong */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"/* Hiệu ứng khi ô nhập liệu được chọn */\n"
"QLineEdit:focus {\n"
"    border: 1px solid #4a90e2; /* Viền xanh khi focus */\n"
"    background-color: #e6f0fa; /* Nền xanh nhạt khi focus */\n"
"}")
        self.line_id.setObjectName("line_id")
        self.verticalLayout.addWidget(self.line_id)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(16)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.line_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_name.setMinimumSize(QtCore.QSize(120, 35))
        self.line_name.setMaximumSize(QtCore.QSize(129, 35))
        self.line_name.setStyleSheet("QLineEdit {\n"
"    background-color: #ffffff; /* Màu nền trắng */\n"
"    border: 1px solid #cccccc; /* Viền xám nhạt */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 5px; /* Khoảng cách bên trong */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"/* Hiệu ứng khi ô nhập liệu được chọn */\n"
"QLineEdit:focus {\n"
"    border: 1px solid #4a90e2; /* Viền xanh khi focus */\n"
"    background-color: #e6f0fa; /* Nền xanh nhạt khi focus */\n"
"}")
        self.line_name.setObjectName("line_name")
        self.verticalLayout_4.addWidget(self.line_name)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(38, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.line_pass = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_pass.setMinimumSize(QtCore.QSize(120, 35))
        self.line_pass.setMaximumSize(QtCore.QSize(120, 16777215))
        self.line_pass.setStyleSheet("QLineEdit {\n"
"    background-color: #ffffff; /* Màu nền trắng */\n"
"    border: 1px solid #cccccc; /* Viền xám nhạt */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 5px; /* Khoảng cách bên trong */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"/* Hiệu ứng khi ô nhập liệu được chọn */\n"
"QLineEdit:focus {\n"
"    border: 1px solid #4a90e2; /* Viền xanh khi focus */\n"
"    background-color: #e6f0fa; /* Nền xanh nhạt khi focus */\n"
"}")
        self.line_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_pass.setObjectName("line_pass")
        self.verticalLayout_7.addWidget(self.line_pass)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(754, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.line_fullName = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_fullName.setMinimumSize(QtCore.QSize(300, 35))
        self.line_fullName.setStyleSheet("QLineEdit {\n"
"    background-color: #ffffff; /* Màu nền trắng */\n"
"    border: 1px solid #cccccc; /* Viền xám nhạt */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 5px; /* Khoảng cách bên trong */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"/* Hiệu ứng khi ô nhập liệu được chọn */\n"
"QLineEdit:focus {\n"
"    border: 1px solid #4a90e2; /* Viền xanh khi focus */\n"
"    background-color: #e6f0fa; /* Nền xanh nhạt khi focus */\n"
"}")
        self.line_fullName.setObjectName("line_fullName")
        self.verticalLayout_5.addWidget(self.line_fullName)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.line_phoneNum = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_phoneNum.setMinimumSize(QtCore.QSize(300, 35))
        self.line_phoneNum.setStyleSheet("QLineEdit {\n"
"    background-color: #ffffff; /* Màu nền trắng */\n"
"    border: 1px solid #cccccc; /* Viền xám nhạt */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 5px; /* Khoảng cách bên trong */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"/* Hiệu ứng khi ô nhập liệu được chọn */\n"
"QLineEdit:focus {\n"
"    border: 1px solid #4a90e2; /* Viền xanh khi focus */\n"
"    background-color: #e6f0fa; /* Nền xanh nhạt khi focus */\n"
"}")
        self.line_phoneNum.setObjectName("line_phoneNum")
        self.verticalLayout_2.addWidget(self.line_phoneNum)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(754, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 3, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.line_salary = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_salary.setMinimumSize(QtCore.QSize(300, 35))
        self.line_salary.setStyleSheet("QLineEdit {\n"
"    background-color: #ffffff; /* Màu nền trắng */\n"
"    border: 1px solid #cccccc; /* Viền xám nhạt */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 5px; /* Khoảng cách bên trong */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"/* Hiệu ứng khi ô nhập liệu được chọn */\n"
"QLineEdit:focus {\n"
"    border: 1px solid #4a90e2; /* Viền xanh khi focus */\n"
"    background-color: #e6f0fa; /* Nền xanh nhạt khi focus */\n"
"}")
        self.line_salary.setObjectName("line_salary")
        self.verticalLayout_3.addWidget(self.line_salary)
        self.gridLayout.addLayout(self.verticalLayout_3, 4, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(17, 19, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 5, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.line_email = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_email.setMinimumSize(QtCore.QSize(715, 35))
        self.line_email.setStyleSheet("QLineEdit {\n"
"    background-color: #ffffff; /* Màu nền trắng */\n"
"    border: 1px solid #cccccc; /* Viền xám nhạt */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 5px; /* Khoảng cách bên trong */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"/* Hiệu ứng khi ô nhập liệu được chọn */\n"
"QLineEdit:focus {\n"
"    border: 1px solid #4a90e2; /* Viền xanh khi focus */\n"
"    background-color: #e6f0fa; /* Nền xanh nhạt khi focus */\n"
"}")
        self.line_email.setObjectName("line_email")
        self.verticalLayout_6.addWidget(self.line_email)
        self.gridLayout.addLayout(self.verticalLayout_6, 6, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 7, 0, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_8.addWidget(self.label_9)
        self.line_address = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_address.setMinimumSize(QtCore.QSize(715, 35))
        self.line_address.setStyleSheet("QLineEdit {\n"
"    background-color: #ffffff; /* Màu nền trắng */\n"
"    border: 1px solid #cccccc; /* Viền xám nhạt */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 5px; /* Khoảng cách bên trong */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"/* Hiệu ứng khi ô nhập liệu được chọn */\n"
"QLineEdit:focus {\n"
"    border: 1px solid #4a90e2; /* Viền xanh khi focus */\n"
"    background-color: #e6f0fa; /* Nền xanh nhạt khi focus */\n"
"}")
        self.line_address.setObjectName("line_address")
        self.verticalLayout_8.addWidget(self.line_address)
        self.gridLayout.addLayout(self.verticalLayout_8, 8, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(179, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 9, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(20, -1, -1, 33)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.them_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.them_btn.setMinimumSize(QtCore.QSize(80, 40))
        self.them_btn.setStyleSheet("QPushButton {\n"
"    background-color:  rgba(30, 170, 255, 0.7); /* Nền xanh trong suốt */\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    border-radius: 16px;\n"
"    padding: 8px 16px;\n"
"    \n"
"    /* Viền sáng */\n"
"    border: 1.5px solid rgba(255, 255, 255, 0.4);\n"
"    \n"
"    /* Đổ bóng - QSS hỗ trợ giới hạn */\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    \n"
"    /* Gradient xanh */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(30, 170, 255, 0.5); /* Xanh sáng hơn khi hover */\n"
"    border: 1.5px solid rgba(255, 255, 255, 0.6);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 120, 200, 0.4);\n"
"    border: 1.5px solid rgba(255, 255, 255, 0.3);\n"
"    padding-top: 9px; /* Tạo hiệu ứng nhấn xuống */\n"
"    padding-left: 17px;\n"
"}\n"
"")
        self.them_btn.setText("")
        self.them_btn.setObjectName("them_btn")
        self.horizontalLayout.addWidget(self.them_btn)
        self.huy_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.huy_btn.setMinimumSize(QtCore.QSize(80, 40))
        self.huy_btn.setStyleSheet("#huy_btn {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #d9d9d9;\n"
"    font-family: Arial, sans-serif;\n"
"    font-size: 12px;\n"
"    border-radius: 10px;\n"
"    padding: 5px 15px; /* Khoảng cách trong nút */\n"
"}\n"
"\n"
"/* Hover effect */\n"
"#huy_btn:hover {\n"
"    background-color: #f5f5f5;  /* Nhẹ hơn để tạo hiệu ứng phản hồi */\n"
"    border: 1px solid #a0a0a0;  /* Viền đậm hơn một chút khi hover */\n"
"    color: black;\n"
"}\n"
"")
        self.huy_btn.setObjectName("huy_btn")
        self.horizontalLayout.addWidget(self.huy_btn)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        spacerItem8 = QtWidgets.QSpacerItem(602, 71, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.gridLayout.addLayout(self.horizontalLayout_4, 10, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Thêm danh mục"))
        self.label.setText(_translate("Form", "ID nhân viên : "))
        self.line_id.setPlaceholderText(_translate("Form", "ID Nhân viên..."))
        self.label_5.setText(_translate("Form", "Tên đăng nhập :"))
        self.line_name.setPlaceholderText(_translate("Form", "Tên đăng nhập..."))
        self.label_8.setText(_translate("Form", "Mật khẩu : "))
        self.line_pass.setPlaceholderText(_translate("Form", "Mật khẩu..."))
        self.label_6.setText(_translate("Form", "Họ và tên :"))
        self.line_fullName.setPlaceholderText(_translate("Form", "Họ và tên..."))
        self.label_2.setText(_translate("Form", "Số điện thoại :"))
        self.line_phoneNum.setPlaceholderText(_translate("Form", "Số điện thoại..."))
        self.label_4.setText(_translate("Form", "Lương :"))
        self.line_salary.setPlaceholderText(_translate("Form", "Lương..."))
        self.label_7.setText(_translate("Form", "Email :"))
        self.line_email.setPlaceholderText(_translate("Form", "Email..."))
        self.label_9.setText(_translate("Form", "Địa chỉ :"))
        self.line_address.setPlaceholderText(_translate("Form", "Địa chỉ..."))
        self.huy_btn.setText(_translate("Form", "Hủy"))
