# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_design/add_promotion.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(720, 813)
        Form.setStyleSheet("#Form {\n"
"background: #F5F5F5;\n"
"border-bottom-radius : 10px;\n"
"border : 2px solid white ;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Form)
        self.centralwidget.setGeometry(QtCore.QRect(0, 0, 720, 751))
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 751))
        self.centralwidget.setObjectName("centralwidget")
        self.them_sua_label = QtWidgets.QLabel(self.centralwidget)
        self.them_sua_label.setGeometry(QtCore.QRect(0, 0, 720, 55))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.them_sua_label.setFont(font)
        self.them_sua_label.setStyleSheet("QLabel {\n"
"    background-color:  rgba(40, 40, 40, 180); /* Nền xanh trong suốt */\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"\n"
"    padding: 8px 16px;\n"
"    \n"
"    /* Viền sáng */\n"
"    border: 1.5px solid rgba(255, 255, 255, 0.4);\n"
"    \n"
"    /* Đổ bóng - QSS hỗ trợ giới hạn */\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    \n"
"    /* Gradient xanh */\n"
"}\n"
"\n"
"")
        self.them_sua_label.setText("")
        self.them_sua_label.setObjectName("them_sua_label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 60, 616, 684))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.table_widget = QtWidgets.QWidget(self.layoutWidget)
        self.table_widget.setMinimumSize(QtCore.QSize(614, 398))
        self.table_widget.setStyleSheet("/* Tổng thể bảng với phong cách Glassmorphism */\n"
"QTableWidget {\n"
"    background-color:  rgba(40, 40, 40, 180); /* Nền đen mờ, tăng độ trong suốt */\n"
"    border: 1px solid rgba(255, 255, 255, 0.2); /* Viền trắng mờ nhẹ */\n"
"    border-radius: 10px; /* Bo góc mềm mại */\n"
"    color: #ffffff; /* Chữ trắng để nổi bật */\n"
"    font-family: \"Arial\", sans-serif;\n"
"    font-size: 14px;\n"
"    gridline-color: transparent;\n"
"}\n"
"\n"
"/* Tiêu đề cột (header) */\n"
"QHeaderView::section {\n"
"    background-color: rgba(30, 30, 30, 180);\n"
" /* Nền header đen mờ hơn một chút */\n"
"    color: #ffffff;\n"
"    padding: 8px;\n"
"    border: none;\n"
"    border-bottom: 1px solid rgba(255, 255, 255, 0.2);\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Hiệu ứng hover cho tiêu đề */\n"
"QHeaderView::section:hover {\n"
"    background-color: rgba(0, 0, 0, 0.6); /* Sáng nhẹ khi hover */\n"
"    transition: background-color 0.3s ease; /* Hiệu ứng chuyển màu mượt */\n"
"}\n"
"\n"
"/* Các ô trong bảng */\n"
"QTableWidget::item {\n"
"    padding: 8px;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/* Hiệu ứng khi chọn ô */\n"
"QTableWidget::item:selected {\n"
"    background-color: rgba(66, 165, 245, 0.4); /* Màu xanh dương mờ khi chọn */\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* Hiệu ứng hover cho ô */\n"
"QTableWidget::item:hover {\n"
"    background-color: rgba(255, 255, 255, 0.1); /* Sáng nhẹ khi rê chuột */\n"
"    transition: background-color 0.3s ease; /* Chuyển màu mượt mà */\n"
"}\n"
"\n"
"/* Thanh cuộn dọc */\n"
"QScrollBar:vertical {\n"
"    background: rgba(0, 0, 0, 0.3); /* Nền đen mờ hơn */\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: linear-gradient(to bottom, rgba(66, 165, 245, 0.6), rgba(30, 136, 229, 0.6)); /* Gradient xanh dương mờ */\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: linear-gradient(to bottom, rgba(100, 181, 246, 0.7), rgba(66, 165, 245, 0.7)); /* Sáng hơn khi hover */\n"
"    transition: background 0.3s ease;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* Thanh cuộn ngang */\n"
"QScrollBar:horizontal {\n"
"    background: rgba(0, 0, 0, 0.3); /* Nền đen mờ hơn */\n"
"    height: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: linear-gradient(to right, rgba(66, 165, 245, 0.6), rgba(30, 136, 229, 0.6)); /* Gradient xanh dương mờ */\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: linear-gradient(to right, rgba(100, 181, 246, 0.7), rgba(66, 165, 245, 0.7)); /* Sáng hơn khi hover */\n"
"    transition: background 0.3s ease;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal,\n"
"QScrollBar::sub-line:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal,\n"
"QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}")
        self.table_widget.setObjectName("table_widget")
        self.widget = QtWidgets.QWidget(self.table_widget)
        self.widget.setGeometry(QtCore.QRect(20, 389, 120, 61))
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.table_widget, 3, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.input_Id_khuyenmai = QtWidgets.QLineEdit(self.layoutWidget)
        self.input_Id_khuyenmai.setMinimumSize(QtCore.QSize(610, 35))
        self.input_Id_khuyenmai.setStyleSheet("QLineEdit {\n"
"    background-color: #ffffff; /* Màu nền trắng */\n"
"    border: 1px solid #cccccc; /* Viền xám nhạt */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 5px; /* Khoảng cách bên trong */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"/* Hiệu ứng khi ô nhập liệu được chọn */\n"
"QLineEdit:focus {\n"
"    border: 1px solid #4a90e2; /* Viền xanh khi focus */\n"
"    background-color: #e6f0fa; /* Nền xanh nhạt khi focus */\n"
"}")
        self.input_Id_khuyenmai.setObjectName("input_Id_khuyenmai")
        self.verticalLayout.addWidget(self.input_Id_khuyenmai)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.input_ten_khuyenmai = QtWidgets.QLineEdit(self.layoutWidget)
        self.input_ten_khuyenmai.setMinimumSize(QtCore.QSize(610, 35))
        self.input_ten_khuyenmai.setStyleSheet("QLineEdit {\n"
"    background-color: #ffffff; /* Màu nền trắng */\n"
"    border: 1px solid #cccccc; /* Viền xám nhạt */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 5px; /* Khoảng cách bên trong */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"/* Hiệu ứng khi ô nhập liệu được chọn */\n"
"QLineEdit:focus {\n"
"    border: 1px solid #4a90e2; /* Viền xanh khi focus */\n"
"    background-color: #e6f0fa; /* Nền xanh nhạt khi focus */\n"
"}")
        self.input_ten_khuyenmai.setObjectName("input_ten_khuyenmai")
        self.verticalLayout_2.addWidget(self.input_ten_khuyenmai)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 18)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(71, 27))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.start_date = QtWidgets.QDateEdit(self.layoutWidget)
        self.start_date.setMinimumSize(QtCore.QSize(161, 30))
        self.start_date.setStyleSheet("QDateEdit {\n"
"    background-color:  rgba(40, 40, 40, 180); /* Nền xanh trong suốt */\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"\n"
"    padding: 8px 16px;\n"
"    \n"
"    /* Viền sáng */\n"
"    border: 1.5px solid rgba(255, 255, 255, 0.4);\n"
"    \n"
"    /* Đổ bóng - QSS hỗ trợ giới hạn */\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    \n"
"    /* Gradient xanh */\n"
"}\n"
"\n"
"")
        self.start_date.setObjectName("start_date")
        self.verticalLayout_3.addWidget(self.start_date)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(71, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.end_date = QtWidgets.QDateEdit(self.layoutWidget)
        self.end_date.setMinimumSize(QtCore.QSize(161, 30))
        self.end_date.setStyleSheet("QDateEdit {\n"
"    background-color:  rgba(40, 40, 40, 180); /* Nền xanh trong suốt */\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"\n"
"    padding: 8px 16px;\n"
"    \n"
"    /* Viền sáng */\n"
"    border: 1.5px solid rgba(255, 255, 255, 0.4);\n"
"    \n"
"    /* Đổ bóng - QSS hỗ trợ giới hạn */\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    \n"
"    /* Gradient xanh */\n"
"}\n"
"\n"
"")
        self.end_date.setObjectName("end_date")
        self.verticalLayout_4.addWidget(self.end_date)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.them_btn = QtWidgets.QPushButton(Form)
        self.them_btn.setGeometry(QtCore.QRect(50, 760, 80, 40))
        self.them_btn.setMinimumSize(QtCore.QSize(80, 40))
        self.them_btn.setStyleSheet("QPushButton {\n"
"    background-color:  rgba(30, 170, 255, 0.7); /* Nền xanh trong suốt */\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    border-radius: 16px;\n"
"    padding: 8px 16px;\n"
"    \n"
"    /* Viền sáng */\n"
"    border: 1.5px solid rgba(255, 255, 255, 0.4);\n"
"    \n"
"    /* Đổ bóng - QSS hỗ trợ giới hạn */\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    \n"
"    /* Gradient xanh */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(30, 170, 255, 0.5); /* Xanh sáng hơn khi hover */\n"
"    border: 1.5px solid rgba(255, 255, 255, 0.6);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 120, 200, 0.4);\n"
"    border: 1.5px solid rgba(255, 255, 255, 0.3);\n"
"    padding-top: 9px; /* Tạo hiệu ứng nhấn xuống */\n"
"    padding-left: 17px;\n"
"}\n"
"")
        self.them_btn.setObjectName("them_btn")
        self.huy_btn = QtWidgets.QPushButton(Form)
        self.huy_btn.setGeometry(QtCore.QRect(140, 760, 80, 40))
        self.huy_btn.setMinimumSize(QtCore.QSize(80, 40))
        self.huy_btn.setStyleSheet("#huy_btn {\n"
" background-color: white;   /* Màu xanh dương Facebook-like */\n"
"  color: black;                /* Màu chữ */\n"
"           /* Khoảng cách trong nút */\n"
"  border: 1px solid #d9d9d9;   /* Viền xám nhạt hơn */\n"
"  font-family: Arial, sans-serif;\n"
"  font-size: 12px;\n"
"  border-radius: 10px;          /* Bo nhẹ góc (tuỳ chọn) */\n"
"\n"
"}")
        self.huy_btn.setObjectName("huy_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "MainWindow"))
        self.label_2.setText(_translate("Form", "ID khuyến mãi : "))
        self.input_Id_khuyenmai.setPlaceholderText(_translate("Form", "ID Khuyến mãi..."))
        self.label_3.setText(_translate("Form", "Tên khuyến mãi : "))
        self.input_ten_khuyenmai.setPlaceholderText(_translate("Form", "Tên khuyến mãi.."))
        self.label_5.setText(_translate("Form", "Từ ngày : "))
        self.label_6.setText(_translate("Form", "Đến ngày : "))
        self.them_btn.setText(_translate("Form", "Thêm"))
        self.huy_btn.setText(_translate("Form", "Hủy"))
