# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_design/confirm.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(481, 315)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 68, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(93, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(29)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman,serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    color: #8b5e3c; /* Màu chữ nâu vintage */\n"
"    font-family: \"Times New Roman\", serif; /* Font chữ cổ điển */\n"
"    font-style: italic; /* Chữ in nghiêng */\n"
"    font-weight: bold;\n"
"    font-size: 30px;\n"
"    padding: 8px;\n"
"\n"
"    text-align: center;\n"
"}\n"
"\n"
"\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman,serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    color: #8b5e3c; /* Màu chữ nâu vintage */\n"
"    font-family: \"Times New Roman\", serif; /* Font chữ cổ điển */\n"
"    font-style: italic; /* Chữ in nghiêng */\n"
"    font-weight: bold;\n"
"    font-size: 30px;\n"
"    padding: 8px;\n"
"\n"
"    text-align: center;\n"
"}\n"
"\n"
"\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(110, -1, 110, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.yes_btn = QtWidgets.QPushButton(Form)
        self.yes_btn.setStyleSheet("QPushButton {\n"
"    background-color: #d4a373; /* Màu nền vintage */\n"
"    color: #ffffff; /* Màu chữ trắng */\n"
"    border: 2px solid #8c5c3f; /* Viền màu nâu đậm */\n"
"    border-radius: 10px; /* Bo góc mềm mại */\n"
"    font-family: \"Georgia\", serif; /* Font chữ cổ điển */\n"
"    font-size: 10px; /* Kích thước chữ */\n"
"    font-weight: bold; /* Chữ đậm */\n"
"    padding: 10px 20px; /* Khoảng cách bên trong nút */\n"
"    text-transform: uppercase; /* Chữ in hoa */\n"
"    box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.3); /* Hiệu ứng bóng */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #c28e62; /* Màu nền khi hover */\n"
"    box-shadow: 3px 3px 7px rgba(0, 0, 0, 0.4); /* Bóng khi hover */\n"
"    transform: scale(1.05); /* Hiệu ứng phóng to nhẹ */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #a67c55; /* Màu nền khi nhấn */\n"
"    box-shadow: inset 2px 2px 5px rgba(0, 0, 0, 0.3); /* Hiệu ứng bóng khi nhấn */\n"
"    transform: scale(0.95); /* Hiệu ứng thu nhỏ nhẹ */\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #8c5c3f; /* Màu nền khi nút được chọn */\n"
"    color: #f4f1e9; /* Màu chữ khi chọn */\n"
"    border: 2px solid #6b3f2b; /* Viền đậm hơn */\n"
"    box-shadow: inset 3px 3px 6px rgba(0, 0, 0, 0.4); /* Hiệu ứng bóng bên trong */\n"
"    transform: scale(1); /* Giữ nguyên kích thước */\n"
"}\n"
"")
        self.yes_btn.setObjectName("yes_btn")
        self.horizontalLayout.addWidget(self.yes_btn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.no_btn = QtWidgets.QPushButton(Form)
        self.no_btn.setStyleSheet("#no_btn {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #d9d9d9;\n"
"    font-family: Arial, sans-serif;\n"
"    font-size: 12px;\n"
"    border-radius: 10px;\n"
"    padding: 10px 20px; /* Khoảng cách trong nút */\n"
"}\n"
"\n"
"/* Hover effect */\n"
"#no_btn:hover {\n"
"    background-color: #f5f5f5;  /* Nhẹ hơn để tạo hiệu ứng phản hồi */\n"
"    border: 1px solid #a0a0a0;  /* Viền đậm hơn một chút khi hover */\n"
"    color: black;\n"
"}\n"
"")
        self.no_btn.setObjectName("no_btn")
        self.horizontalLayout.addWidget(self.no_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(93, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 67, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 2, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "BẠN CÓ CHẮC CHẮN "))
        self.label_2.setText(_translate("Form", "MUỐN XÓA SẢN PHẨM NÀY ?"))
        self.yes_btn.setText(_translate("Form", "Có"))
        self.no_btn.setText(_translate("Form", "Không"))
