# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_design/warehouse_detail.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 400)
        Form.setStyleSheet("#Form {\n"
"background: #F5F5F5;\n"
"border-bottom-radius : 10px;\n"
"border : 2px solid white ;\n"
"}")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 40))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("QLabel {\n"
"    background-color:  rgba(40, 40, 40, 180); /* Nền xanh trong suốt */\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"\n"
"    \n"
"    /* Viền sáng */\n"
"    border: 1.5px solid rgba(255, 255, 255, 0.4);\n"
"    \n"
"    /* Đổ bóng - QSS hỗ trợ giới hạn */\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    \n"
"    /* Gradient xanh */\n"
"}\n"
"\n"
"")
        self.label.setObjectName("label")
        self.inf_kho_2 = QtWidgets.QWidget(Form)
        self.inf_kho_2.setGeometry(QtCore.QRect(60, 60, 501, 301))
        self.inf_kho_2.setStyleSheet("QWidget {\n"
"    border: 1px solid rgba(60, 60, 60, 0.8); /* Viền mỏng màu xám đậm */\n"
"    border-radius: 8px; /* Bo góc mềm mại hơn */\n"
"    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.15); /* Thêm đổ bóng nhẹ */\n"
"    background-color: rgba(245, 245, 245, 0.5); /* Nền trắng đục nhẹ */\n"
"    padding: 2px; /* Thêm padding nhỏ */\n"
"}\n"
"")
        self.inf_kho_2.setObjectName("inf_kho_2")
        self.lable_kho_1 = QtWidgets.QLabel(self.inf_kho_2)
        self.lable_kho_1.setGeometry(QtCore.QRect(4, 5, 491, 291))
        self.lable_kho_1.setText("")
        self.lable_kho_1.setObjectName("lable_kho_1")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "CHI TIẾT KHO"))
