# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_design/sign_up.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main_log(object):
    def setupUi(self, Main_log):
        Main_log.setObjectName("Main_log")
        Main_log.resize(1100, 800)
        font = QtGui.QFont()
        font.setPointSize(10)
        Main_log.setFont(font)
        Main_log.setStyleSheet("#Main_log {\n"
"\n"
"    border-image: url(:/icon/icon/background.jpg);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Main_log)
        self.centralwidget.setStyleSheet("centralwidget {\n"
"border-image: url(:/background/_1 (1).jpg);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setContentsMargins(11, -1, -1, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.mainwidget = QtWidgets.QWidget(self.centralwidget)
        self.mainwidget.setEnabled(True)
        self.mainwidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mainwidget.setToolTipDuration(-1)
        self.mainwidget.setStyleSheet("")
        self.mainwidget.setObjectName("mainwidget")
        self.Container = QtWidgets.QWidget(self.mainwidget)
        self.Container.setEnabled(True)
        self.Container.setGeometry(QtCore.QRect(250, 135, 578, 509))
        self.Container.setStyleSheet("/* Áp dụng cho Container chính */\n"
"#Container {\n"
"    background-color: rgba(40, 40, 40, 180);\n"
"    border-radius: 10px;\n"
"    border: 1px solid rgba(60, 60, 60, 200);\n"
"    color: white;\n"
"}\n"
"\n"
"/* Đặt lại thuộc tính cho các widget con */\n"
"QLineEdit {\n"
"    background-color: rgba(255, 255, 255, 220);\n"
"    color: black;\n"
"    border: 1px solid gray;\n"
"    border-radius: 5px;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: rgba(70, 130, 180, 200);\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"")
        self.Container.setObjectName("Container")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Container)
        self.gridLayout_2.setContentsMargins(50, 18, 50, 30)
        self.gridLayout_2.setVerticalSpacing(7)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(0, -1, -1, -1)
        self.gridLayout.setHorizontalSpacing(9)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.Container)
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("\n"
"color: rgb(255,255,255); /* Đổi thành màu trắng */\n"
"\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.sdt_email_line = QtWidgets.QLineEdit(self.Container)
        self.sdt_email_line.setEnabled(True)
        self.sdt_email_line.setMinimumSize(QtCore.QSize(380, 50))
        self.sdt_email_line.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    border: 2px solid rgba(0, 0, 0, 0);\n"
"    border-bottom: 2px solid rgba(255, 255, 255, 200);\n"
"    color: rgb(255, 255, 255);\n"
"    padding-bottom: 7px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid rgba(255, 255, 255, 255); /* Sáng hơn khi hover */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid rgba(0, 170, 255, 255); /* Đổi màu khi nhập */\n"
"    outline: none;\n"
"}\n"
"")
        self.sdt_email_line.setObjectName("sdt_email_line")
        self.verticalLayout.addWidget(self.sdt_email_line)
        self.username_line = QtWidgets.QLineEdit(self.Container)
        self.username_line.setEnabled(True)
        self.username_line.setMinimumSize(QtCore.QSize(350, 50))
        self.username_line.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    border: 2px solid rgba(0, 0, 0, 0);\n"
"    border-bottom: 2px solid rgba(255, 255, 255, 200);\n"
"    color: rgb(255, 255, 255);\n"
"    padding-bottom: 7px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid rgba(255, 255, 255, 255); /* Sáng hơn khi hover */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid rgba(0, 170, 255, 255); /* Đổi màu khi nhập */\n"
"    outline: none;\n"
"}\n"
"")
        self.username_line.setObjectName("username_line")
        self.verticalLayout.addWidget(self.username_line)
        self.password_line = QtWidgets.QLineEdit(self.Container)
        self.password_line.setMinimumSize(QtCore.QSize(0, 50))
        self.password_line.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    border: 2px solid rgba(0, 0, 0, 0);\n"
"    border-bottom: 2px solid rgba(255, 255, 255, 200);\n"
"    color: rgb(255, 255, 255);\n"
"    padding-bottom: 7px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid rgba(255, 255, 255, 255); /* Sáng hơn khi hover */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid rgba(0, 170, 255, 255); /* Đổi màu khi nhập */\n"
"    outline: none;\n"
"}\n"
"")
        self.password_line.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_line.setObjectName("password_line")
        self.verticalLayout.addWidget(self.password_line)
        self.cpass_line = QtWidgets.QLineEdit(self.Container)
        self.cpass_line.setEnabled(True)
        self.cpass_line.setMinimumSize(QtCore.QSize(350, 50))
        self.cpass_line.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    border: 2px solid rgba(0, 0, 0, 0);\n"
"    border-bottom: 2px solid rgba(255, 255, 255, 200);\n"
"    color: rgb(255, 255, 255);\n"
"    padding-bottom: 7px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid rgba(255, 255, 255, 255); /* Sáng hơn khi hover */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid rgba(0, 170, 255, 255); /* Đổi màu khi nhập */\n"
"    outline: none;\n"
"}\n"
"")
        self.cpass_line.setEchoMode(QtWidgets.QLineEdit.Password)
        self.cpass_line.setObjectName("cpass_line")
        self.verticalLayout.addWidget(self.cpass_line)
        self.gridLayout.addLayout(self.verticalLayout, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 3, 0, 1, 1)
        self.signup_btn = QtWidgets.QPushButton(self.Container)
        self.signup_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0.6);\n"
"    color: white;\n"
"    border: 1px solid white;\n"
"    border-radius: 20px;\n"
"    padding: 8px 16px;\n"
"    font-weight: bold;\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 107, 53, 0.8);\n"
"    border: 1px solid #ff6b35;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 107, 53, 1);\n"
"    border: 1px solid white;\n"
"}\n"
"")
        self.signup_btn.setObjectName("signup_btn")
        self.gridLayout.addWidget(self.signup_btn, 4, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 1, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 2, 1, 1, 1)
        self.back_btn = QtWidgets.QPushButton(self.mainwidget)
        self.back_btn.setGeometry(QtCore.QRect(30, 20, 41, 28))
        self.back_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0.6);\n"
"    color: white;\n"
"    border: 1px solid white;\n"
"    border-radius: 8px;\n"
"    padding: 8px 16px;\n"
"    font-weight: bold;\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 107, 53, 0.8);\n"
"    border: 1px solid #ff6b35;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 107, 53, 1);\n"
"    border: 1px solid white;\n"
"}\n"
"")
        self.back_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/arrow-96-xxl.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_btn.setIcon(icon)
        self.back_btn.setObjectName("back_btn")
        self.label_18 = QtWidgets.QLabel(self.mainwidget)
        self.label_18.setGeometry(QtCore.QRect(10, 750, 1056, 16))
        self.label_18.setMinimumSize(QtCore.QSize(1051, 16))
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_18.setStyleSheet("color: rgb(30, 30, 30);\n"
"")
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.mainwidget, 0, 0, 1, 1)
        Main_log.setCentralWidget(self.centralwidget)

        self.retranslateUi(Main_log)
        QtCore.QMetaObject.connectSlotsByName(Main_log)

    def retranslateUi(self, Main_log):
        _translate = QtCore.QCoreApplication.translate
        Main_log.setWindowTitle(_translate("Main_log", "MainWindow"))
        self.label_3.setText(_translate("Main_log", "ĐĂNG KÝ"))
        self.sdt_email_line.setPlaceholderText(_translate("Main_log", "Số điiện thoại hoặc Email..."))
        self.username_line.setPlaceholderText(_translate("Main_log", "Tên đăng nhập..."))
        self.password_line.setPlaceholderText(_translate("Main_log", "Mật khẩu..."))
        self.cpass_line.setPlaceholderText(_translate("Main_log", "Xác nhận mật khẩu..."))
        self.signup_btn.setText(_translate("Main_log", "Đ Ă N G   K Ý"))
        self.label_18.setText(_translate("Main_log", "   © 2025 Le Huu Tri - Nguyen Minh Tu - Do Xuan Tri . All rights reserved."))

