# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_design/add_customer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 300)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 800, 45))
        self.label_3.setMinimumSize(QtCore.QSize(800, 45))
        self.label_3.setStyleSheet("QLabel {\n"
"    background-color: #d4a373; /* Màu nền vintage */\n"
"    color: #ffffff; /* Màu chữ trắng */\n"
"    border: 2px solid #8c5c3f; /* Viền màu nâu đậm */\n"
"    font-family: \"Georgia\", serif; /* Font chữ cổ điển */\n"
"    font-size: 14px; /* Kích thước chữ */\n"
"    font-weight: bold; /* Chữ đậm */\n"
"    padding: 5px 10px; /* Khoảng cách bên trong nút */\n"
"    text-transform: uppercase; /* Chữ in hoa */\n"
"    box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.3); /* Hiệu ứng bóng */\n"
"}")
        self.label_3.setObjectName("label_3")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 40, 801, 270))
        self.widget.setObjectName("widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(20, 20, 20, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.line_id = QtWidgets.QLineEdit(self.widget)
        self.line_id.setMinimumSize(QtCore.QSize(300, 35))
        self.line_id.setStyleSheet("QLineEdit {\n"
"background-color:white;\n"
"border : 1px solid grey;\n"
"border-radius : 10px;\n"
"}\n"
"QLineEdit:hover{\n"
"border : 2px solid #e67e22;\n"
"}\n"
"")
        self.line_id.setObjectName("line_id")
        self.verticalLayout.addWidget(self.line_id)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.line_name = QtWidgets.QLineEdit(self.widget)
        self.line_name.setMinimumSize(QtCore.QSize(300, 35))
        self.line_name.setStyleSheet("QLineEdit {\n"
"background-color:white;\n"
"border : 1px solid grey;\n"
"border-radius : 10px;\n"
"}\n"
"QLineEdit:hover{\n"
"border : 2px solid #e67e22;\n"
"}\n"
"")
        self.line_name.setObjectName("line_name")
        self.verticalLayout_4.addWidget(self.line_name)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(757, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.dateEdit = QtWidgets.QDateEdit(self.widget)
        self.dateEdit.setMinimumSize(QtCore.QSize(300, 35))
        self.dateEdit.setStyleSheet("QDateEdit {\n"
"background-color:white;\n"
"border : 1px solid grey;\n"
"border-radius : 10px;\n"
"}\n"
"QDateEdit:hover{\n"
"border : 2px solid #e67e22;\n"
"}\n"
"")
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout_3.addWidget(self.dateEdit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.line_phoneNum = QtWidgets.QLineEdit(self.widget)
        self.line_phoneNum.setMinimumSize(QtCore.QSize(300, 35))
        self.line_phoneNum.setStyleSheet("QLineEdit {\n"
"background-color:white;\n"
"border : 1px solid grey;\n"
"border-radius : 10px;\n"
"}\n"
"QLineEdit:hover{\n"
"border : 2px solid #e67e22;\n"
"}\n"
"")
        self.line_phoneNum.setObjectName("line_phoneNum")
        self.verticalLayout_2.addWidget(self.line_phoneNum)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(185, 21, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(20, -1, -1, 33)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.them_btn = QtWidgets.QPushButton(self.widget)
        self.them_btn.setMinimumSize(QtCore.QSize(80, 40))
        self.them_btn.setStyleSheet("QPushButton {\n"
"    background-color: #d4a373; /* Màu nền vintage */\n"
"    color: #ffffff; /* Màu chữ trắng */\n"
"    border: 2px solid #8c5c3f; /* Viền màu nâu đậm */\n"
"    border-radius: 10px; /* Bo góc mềm mại */\n"
"    font-family: \"Georgia\", serif; /* Font chữ cổ điển */\n"
"    font-size: 10px; /* Kích thước chữ */\n"
"    font-weight: bold; /* Chữ đậm */\n"
"    padding: 5px 10px; /* Khoảng cách bên trong nút */\n"
"    text-transform: uppercase; /* Chữ in hoa */\n"
"    box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.3); /* Hiệu ứng bóng */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #c28e62; /* Màu nền khi hover */\n"
"    box-shadow: 3px 3px 7px rgba(0, 0, 0, 0.4); /* Bóng khi hover */\n"
"    transform: scale(1.05); /* Hiệu ứng phóng to nhẹ */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #a67c55; /* Màu nền khi nhấn */\n"
"    box-shadow: inset 2px 2px 5px rgba(0, 0, 0, 0.3); /* Hiệu ứng bóng khi nhấn */\n"
"    transform: scale(0.95); /* Hiệu ứng thu nhỏ nhẹ */\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #8c5c3f; /* Màu nền khi nút được chọn */\n"
"    color: #f4f1e9; /* Màu chữ khi chọn */\n"
"    border: 2px solid #6b3f2b; /* Viền đậm hơn */\n"
"    box-shadow: inset 3px 3px 6px rgba(0, 0, 0, 0.4); /* Hiệu ứng bóng bên trong */\n"
"    transform: scale(1); /* Giữ nguyên kích thước */\n"
"}\n"
"")
        self.them_btn.setObjectName("them_btn")
        self.horizontalLayout.addWidget(self.them_btn)
        self.huy_btn = QtWidgets.QPushButton(self.widget)
        self.huy_btn.setMinimumSize(QtCore.QSize(80, 40))
        self.huy_btn.setStyleSheet("#huy_btn {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #d9d9d9;\n"
"    font-family: Arial, sans-serif;\n"
"    font-size: 12px;\n"
"    border-radius: 10px;\n"
"    padding: 5px 15px; /* Khoảng cách trong nút */\n"
"}\n"
"\n"
"/* Hover effect */\n"
"#huy_btn:hover {\n"
"    background-color: #f5f5f5;  /* Nhẹ hơn để tạo hiệu ứng phản hồi */\n"
"    border: 1px solid #a0a0a0;  /* Viền đậm hơn một chút khi hover */\n"
"    color: black;\n"
"}\n"
"")
        self.huy_btn.setObjectName("huy_btn")
        self.horizontalLayout.addWidget(self.huy_btn)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(602, 71, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Thêm danh mục"))
        self.label_3.setText(_translate("Form", "Thêm khách hàng"))
        self.label.setText(_translate("Form", "ID Khách Hàng"))
        self.line_id.setPlaceholderText(_translate("Form", "ID Nhân viên..."))
        self.label_5.setText(_translate("Form", "Tên Khách hàng"))
        self.line_name.setPlaceholderText(_translate("Form", "Tên đăng nhập..."))
        self.label_6.setText(_translate("Form", "Họ tên"))
        self.label_2.setText(_translate("Form", "Số điện thoại"))
        self.line_phoneNum.setPlaceholderText(_translate("Form", "Số điện thoại..."))
        self.them_btn.setText(_translate("Form", "Thêm"))
        self.huy_btn.setText(_translate("Form", "Hủy"))
