# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_design/add_customer.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 300)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("#Form {\n"
"background: #F5F5F5;\n"
"border-bottom-radius : 10px;\n"
"border : 2px solid white ;\n"
"}")
        self.them_sua_label = QtWidgets.QLabel(Form)
        self.them_sua_label.setGeometry(QtCore.QRect(0, 0, 800, 45))
        self.them_sua_label.setMinimumSize(QtCore.QSize(800, 45))
        self.them_sua_label.setStyleSheet("QLabel {\n"
"    background-color:  rgba(40, 40, 40, 180); /* Nền xanh trong suốt */\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"\n"
"    padding: 8px 16px;\n"
"    \n"
"    /* Viền sáng */\n"
"    border: 1.5px solid rgba(255, 255, 255, 0.4);\n"
"    \n"
"    /* Đổ bóng - QSS hỗ trợ giới hạn */\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    \n"
"    /* Gradient xanh */\n"
"}\n"
"\n"
"")
        self.them_sua_label.setText("")
        self.them_sua_label.setObjectName("them_sua_label")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 40, 801, 270))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(20, 20, 20, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.line_id = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_id.setMinimumSize(QtCore.QSize(300, 35))
        self.line_id.setStyleSheet("QLineEdit {\n"
"    background-color: #ffffff; /* Màu nền trắng */\n"
"    border: 1px solid #cccccc; /* Viền xám nhạt */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 5px; /* Khoảng cách bên trong */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"/* Hiệu ứng khi ô nhập liệu được chọn */\n"
"QLineEdit:focus {\n"
"    border: 1px solid #4a90e2; /* Viền xanh khi focus */\n"
"    background-color: #e6f0fa; /* Nền xanh nhạt khi focus */\n"
"}")
        self.line_id.setObjectName("line_id")
        self.verticalLayout.addWidget(self.line_id)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.line_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_name.setMinimumSize(QtCore.QSize(300, 35))
        self.line_name.setStyleSheet("QLineEdit {\n"
"    background-color: #ffffff; /* Màu nền trắng */\n"
"    border: 1px solid #cccccc; /* Viền xám nhạt */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 5px; /* Khoảng cách bên trong */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"/* Hiệu ứng khi ô nhập liệu được chọn */\n"
"QLineEdit:focus {\n"
"    border: 1px solid #4a90e2; /* Viền xanh khi focus */\n"
"    background-color: #e6f0fa; /* Nền xanh nhạt khi focus */\n"
"}")
        self.line_name.setObjectName("line_name")
        self.verticalLayout_4.addWidget(self.line_name)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(757, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.line_phoneNum = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_phoneNum.setMinimumSize(QtCore.QSize(300, 35))
        self.line_phoneNum.setStyleSheet("QLineEdit {\n"
"    background-color: #ffffff; /* Màu nền trắng */\n"
"    border: 1px solid #cccccc; /* Viền xám nhạt */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 5px; /* Khoảng cách bên trong */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"/* Hiệu ứng khi ô nhập liệu được chọn */\n"
"QLineEdit:focus {\n"
"    border: 1px solid #4a90e2; /* Viền xanh khi focus */\n"
"    background-color: #e6f0fa; /* Nền xanh nhạt khi focus */\n"
"}")
        self.line_phoneNum.setObjectName("line_phoneNum")
        self.verticalLayout_2.addWidget(self.line_phoneNum)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        spacerItem2 = QtWidgets.QSpacerItem(185, 21, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(20, -1, -1, 33)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.them_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.them_btn.setMinimumSize(QtCore.QSize(80, 40))
        self.them_btn.setStyleSheet("QPushButton {\n"
"    background-color:  rgba(30, 170, 255, 0.7); /* Nền xanh trong suốt */\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    border-radius: 16px;\n"
"    padding: 8px 16px;\n"
"    \n"
"    /* Viền sáng */\n"
"    border: 1.5px solid rgba(255, 255, 255, 0.4);\n"
"    \n"
"    /* Đổ bóng - QSS hỗ trợ giới hạn */\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    \n"
"    /* Gradient xanh */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(30, 170, 255, 0.5); /* Xanh sáng hơn khi hover */\n"
"    border: 1.5px solid rgba(255, 255, 255, 0.6);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 120, 200, 0.4);\n"
"    border: 1.5px solid rgba(255, 255, 255, 0.3);\n"
"    padding-top: 9px; /* Tạo hiệu ứng nhấn xuống */\n"
"    padding-left: 17px;\n"
"}\n"
"")
        self.them_btn.setText("")
        self.them_btn.setObjectName("them_btn")
        self.horizontalLayout.addWidget(self.them_btn)
        self.huy_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.huy_btn.setMinimumSize(QtCore.QSize(80, 40))
        self.huy_btn.setStyleSheet("#huy_btn {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #d9d9d9;\n"
"    font-family: Arial, sans-serif;\n"
"    font-size: 12px;\n"
"    border-radius: 10px;\n"
"    padding: 5px 15px; /* Khoảng cách trong nút */\n"
"}\n"
"\n"
"/* Hover effect */\n"
"#huy_btn:hover {\n"
"    background-color: #f5f5f5;  /* Nhẹ hơn để tạo hiệu ứng phản hồi */\n"
"    border: 1px solid #a0a0a0;  /* Viền đậm hơn một chút khi hover */\n"
"    color: black;\n"
"}\n"
"")
        self.huy_btn.setObjectName("huy_btn")
        self.horizontalLayout.addWidget(self.huy_btn)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(602, 71, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Thêm danh mục"))
        self.label.setText(_translate("Form", "ID Khách Hàng"))
        self.line_id.setPlaceholderText(_translate("Form", "ID Nhân viên..."))
        self.label_5.setText(_translate("Form", "Tên Khách hàng"))
        self.line_name.setPlaceholderText(_translate("Form", "Tên đăng nhập..."))
        self.label_2.setText(_translate("Form", "Số điện thoại"))
        self.line_phoneNum.setPlaceholderText(_translate("Form", "Số điện thoại..."))
        self.huy_btn.setText(_translate("Form", "Hủy"))
